### PR TITLE
Challenge 4 pull request

### PR DESCRIPTION
**Pull request by john555**
@chadwalt, @lornatumuhairwe, @Descartess please review my code and provide feedback.
Here is a summary of the latest updates:
- Basic buketlist functionality works
- Forms have meaningful feedback

### CODE REVIEW

**Comment by chadwalt** [comment]
Hi Paul.

Please include the badges for travis and coverall for the tests.

**Comment by Descartess** [comment]
Remove the jquery related functionality for dom manipulation since you lose the virtual dom manipulation utilised by react. 
Remove Account.jsx since its not being used

**Comment by lornatumuhairwe** [comment]
1. First of all, I have cloned your repo and tried to run it following the instructions in your README.md, `gulp sass` doesn't work and so I can't get the min.css files and hence I ran into an error and I can't use the application. Please work on that or clarify your instructions. Because of this, I won't comment on the functionality.
2. I recommend you split the components and the code.
3. I noticed you are using .js on files with jsx code, please check linting configs, jsx should not be in .js files, I think you should rename your files to jsx.
4. Otherwise the code looks clean. Good job!

**Review by chadwalt — COMMENTED** [review]
1. I have seen in your README, that you removed some file paths, and these might be included in your rep.
2. Remove commented out code.

**Pull request closed without merging**
